"""empty message

Revision ID: 4378dfa36b76
Revises: 
Create Date: 2023-08-05 21:40:31.113951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4378dfa36b76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_price', sa.Numeric(precision=15, scale=1), nullable=False))

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_price', sa.Numeric(precision=15, scale=1), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('initial_price')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('initial_price')

    # ### end Alembic commands ###
