"""empty message

Revision ID: a03a04bab6e7
Revises: 
Create Date: 2023-01-13 00:02:01.634718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03a04bab6e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('income')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
