"""empty message

Revision ID: c31f639075dd
Revises: 
Create Date: 2023-07-21 15:08:45.683596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31f639075dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False))
        batch_op.drop_column('amount')

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=15, scale=6), nullable=False))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=False))
        batch_op.drop_column('price')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
