"""empty message

Revision ID: d5a47d5bd75a
Revises: 
Create Date: 2023-08-01 14:12:41.744333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a47d5bd75a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('currency_code')

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('currency_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
