"""empty message

Revision ID: f95635f92e4b
Revises: 9b3117f65dda
Create Date: 2023-07-31 18:41:11.353216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95635f92e4b'
down_revision = '9b3117f65dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_code', sa.String(length=3), nullable=False))

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_code', sa.String(length=3), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('currency_code')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('currency_code')

    # ### end Alembic commands ###
